name: docker-build

on:
  workflow_dispatch:

jobs:

  build-container:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Login 
      uses: docker/login-action@v1
      
      with:
        username: ${secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASS}}
    - name: Build and push to docker hub
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: adamkwolek/bookingapi:latest
