name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
      run:
        working-directory: Booking.Server
jobs:

  build:

    runs-on: ubuntu-latest
    

    steps:
    - name: Login    
    - uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag adamkwolek/bookingapi:latest
    - name: Push the Docker image
      run: docker push adamkwolek/bookingapi:latest
