name: Docker Image CI

on:
    workflow_dispatch:

defaults:
      run:
        working-directory: Booking.Server
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build 
      run: docker build . --tag adamkwolek/bookingapi:latest
    - name: Docker Push
      run: docker push adamkwolek/bookingapi:latest
